assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    # use_controller: "%kernel.debug%"
    filters:
        cssrewrite: ~
        less:
            node: /usr/bin/node
            node_paths: [%kernel.root_dir%/../node_modules]
        
        yui_css:
            jar: "%kernel.root_dir%/Resources/lib/yuicompressor-2.4.8.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/lib/yuicompressor-2.4.8.jar"
    assets:
        # phpgithub_js:
            # filter: ['yui_js']
            # inputs:
            #     - %kernel.root_dir%/../web/bundles/bundle.js
            # output: dist/js/main.js

        phpgithub_css:
            filter: ['yui_css', 'less']
            inputs:
                - %kernel.root_dir%/../web/css/style.less
            output: dist/css/style.css

    # liste les bundles qui contiennent des assets
    bundles:
      - AppBundle